### ISSUE TITLE
Accidentally closing Greenkeeper pull requests

### ISSUE THREAD

**Issue by lee-dohm** [probot/mistaken-pull-closer#2]
Greenkeeper is opening PRs on Electron's website, but they're getting closed: https://github.com/electron/electron.atom.io/pull/827

Ideas about how to fix this:

- Whitelist branches that start with `greenkeeper/`
- Whitelist the @greenkeeper user
- Something else?

/cc @zeke

**Comment by lee-dohm** [comment]
Since bots have to be invited in to a repository or org (they're [like vampires](https://scifi.stackexchange.com/questions/65991/why-do-vampires-have-to-be-invited-in) that way) in order to do any work like opening PRs, mistaken-pull-closer should just ignore any PRs opened by bots.

**Comment by zeke** [comment]
👍
